/**
 * Unique question suffix for CRE createMarket to avoid duplicate questionIds and nonce clashes on retries.
 * The contract uses questionId = keccak256(question, creator, oracle). Appending a run-unique suffix
 * makes each broadcast use a different questionId so retries do not hit QuestionAlreadyExists.
 * Display name is the question without this suffix (stored in DB and returned by API).
 *
 * Nonces: Ethereum nonces are not generated by this app. The signer (CRE forwarder / CRE_ETH_PRIVATE_KEY)
 * has a nonce = eth_getTransactionCount(signer). Each new tx uses the next nonce. "Nonce too low" means
 * that nonce was already used (e.g. a prior tx confirmed or a concurrent run). "Replacement transaction
 * underpriced" means a tx with that nonce is pending and the new one did not increase gas enough to replace it.
 * Using a unique question per send avoids duplicate questionIds on retry; spacing (INTER_CREATE_DELAY_MS in CRE)
 * and avoiding overlapping createMarketsFromBackend runs reduce nonce clashes.
 */

/** Suffix format: space + timestamp (ms) + "-" + index. No curly braces; safe for contract string. */
const SUFFIX_REGEX = /\s\d{10,}-\d+$/;

/**
 * Returns a unique suffix for the given index in a batch. Use when building CRE payloads so each
 * market in the run has a distinct question string (and thus questionId) and retries do not conflict.
 */
export function getQuestionUniqueSuffix(index: number): string {
  return ` ${Date.now()}-${index}`;
}

/**
 * Appends the unique suffix to a display question for use in CRE createMarket payload only.
 */
export function withQuestionUniqueSuffix(displayQuestion: string, index: number): string {
  const trimmed = displayQuestion?.trim() ?? "";
  return trimmed + getQuestionUniqueSuffix(index);
}

/**
 * Removes the unique suffix from a question string so it can be stored or displayed as the
 * display name. Use when persisting market name from chain (getMarket returns the full question).
 */
export function stripQuestionUniqueSuffix(question: string): string {
  if (typeof question !== "string") return "";
  const stripped = question.replace(SUFFIX_REGEX, "");
  return stripped.trimEnd();
}
