"use strict";
// --- KEEEP IN SYNC with exports/wallets/in-app.ts ---
Object.defineProperty(exports, "__esModule", { value: true });
exports.inAppWallet = exports.hasStoredPasskey = exports.unlinkProfile = exports.preAuthenticate = exports.linkProfile = exports.getUserPhoneNumber = exports.getUserEmail = exports.getProfiles = exports.authenticate = exports.isCreateSessionKeySupported = exports.createSessionKey = exports.isExecuteWithSigSupported = exports.executeWithSig = exports.isExecuteSupported = exports.execute = exports.isCreateSessionWithSigSupported = exports.createSessionWithSig = exports.isWildcardSigner = exports.isIsWildcardSignerSupported = exports.isGetTransferPoliciesForSignerSupported = exports.getTransferPoliciesForSigner = exports.isGetSessionStateForSignerSupported = exports.getSessionStateForSigner = exports.isGetSessionExpirationForSignerSupported = exports.getSessionExpirationForSigner = exports.isGetCallPoliciesForSignerSupported = exports.getCallPoliciesForSigner = exports.isEip712DomainSupported = exports.eip712Domain = exports.valueReceivedEvent = exports.sessionCreatedEvent = exports.executedEvent = void 0;
var Executed_js_1 = require("../../extensions/erc7702/__generated__/MinimalAccount/events/Executed.js");
Object.defineProperty(exports, "executedEvent", { enumerable: true, get: function () { return Executed_js_1.executedEvent; } });
var SessionCreated_js_1 = require("../../extensions/erc7702/__generated__/MinimalAccount/events/SessionCreated.js");
Object.defineProperty(exports, "sessionCreatedEvent", { enumerable: true, get: function () { return SessionCreated_js_1.sessionCreatedEvent; } });
var ValueReceived_js_1 = require("../../extensions/erc7702/__generated__/MinimalAccount/events/ValueReceived.js");
Object.defineProperty(exports, "valueReceivedEvent", { enumerable: true, get: function () { return ValueReceived_js_1.valueReceivedEvent; } });
// ERC7702 generated helpers
var eip712Domain_js_1 = require("../../extensions/erc7702/__generated__/MinimalAccount/read/eip712Domain.js");
Object.defineProperty(exports, "eip712Domain", { enumerable: true, get: function () { return eip712Domain_js_1.eip712Domain; } });
Object.defineProperty(exports, "isEip712DomainSupported", { enumerable: true, get: function () { return eip712Domain_js_1.isEip712DomainSupported; } });
var getCallPoliciesForSigner_js_1 = require("../../extensions/erc7702/__generated__/MinimalAccount/read/getCallPoliciesForSigner.js");
Object.defineProperty(exports, "getCallPoliciesForSigner", { enumerable: true, get: function () { return getCallPoliciesForSigner_js_1.getCallPoliciesForSigner; } });
Object.defineProperty(exports, "isGetCallPoliciesForSignerSupported", { enumerable: true, get: function () { return getCallPoliciesForSigner_js_1.isGetCallPoliciesForSignerSupported; } });
var getSessionExpirationForSigner_js_1 = require("../../extensions/erc7702/__generated__/MinimalAccount/read/getSessionExpirationForSigner.js");
Object.defineProperty(exports, "getSessionExpirationForSigner", { enumerable: true, get: function () { return getSessionExpirationForSigner_js_1.getSessionExpirationForSigner; } });
Object.defineProperty(exports, "isGetSessionExpirationForSignerSupported", { enumerable: true, get: function () { return getSessionExpirationForSigner_js_1.isGetSessionExpirationForSignerSupported; } });
var getSessionStateForSigner_js_1 = require("../../extensions/erc7702/__generated__/MinimalAccount/read/getSessionStateForSigner.js");
Object.defineProperty(exports, "getSessionStateForSigner", { enumerable: true, get: function () { return getSessionStateForSigner_js_1.getSessionStateForSigner; } });
Object.defineProperty(exports, "isGetSessionStateForSignerSupported", { enumerable: true, get: function () { return getSessionStateForSigner_js_1.isGetSessionStateForSignerSupported; } });
var getTransferPoliciesForSigner_js_1 = require("../../extensions/erc7702/__generated__/MinimalAccount/read/getTransferPoliciesForSigner.js");
Object.defineProperty(exports, "getTransferPoliciesForSigner", { enumerable: true, get: function () { return getTransferPoliciesForSigner_js_1.getTransferPoliciesForSigner; } });
Object.defineProperty(exports, "isGetTransferPoliciesForSignerSupported", { enumerable: true, get: function () { return getTransferPoliciesForSigner_js_1.isGetTransferPoliciesForSignerSupported; } });
var isWildcardSigner_js_1 = require("../../extensions/erc7702/__generated__/MinimalAccount/read/isWildcardSigner.js");
Object.defineProperty(exports, "isIsWildcardSignerSupported", { enumerable: true, get: function () { return isWildcardSigner_js_1.isIsWildcardSignerSupported; } });
Object.defineProperty(exports, "isWildcardSigner", { enumerable: true, get: function () { return isWildcardSigner_js_1.isWildcardSigner; } });
var createSessionWithSig_js_1 = require("../../extensions/erc7702/__generated__/MinimalAccount/write/createSessionWithSig.js");
Object.defineProperty(exports, "createSessionWithSig", { enumerable: true, get: function () { return createSessionWithSig_js_1.createSessionWithSig; } });
Object.defineProperty(exports, "isCreateSessionWithSigSupported", { enumerable: true, get: function () { return createSessionWithSig_js_1.isCreateSessionWithSigSupported; } });
var execute_js_1 = require("../../extensions/erc7702/__generated__/MinimalAccount/write/execute.js");
Object.defineProperty(exports, "execute", { enumerable: true, get: function () { return execute_js_1.execute; } });
Object.defineProperty(exports, "isExecuteSupported", { enumerable: true, get: function () { return execute_js_1.isExecuteSupported; } });
var executeWithSig_js_1 = require("../../extensions/erc7702/__generated__/MinimalAccount/write/executeWithSig.js");
Object.defineProperty(exports, "executeWithSig", { enumerable: true, get: function () { return executeWithSig_js_1.executeWithSig; } });
Object.defineProperty(exports, "isExecuteWithSigSupported", { enumerable: true, get: function () { return executeWithSig_js_1.isExecuteWithSigSupported; } });
//ACCOUNT
var createSessionKey_js_1 = require("../../extensions/erc7702/account/createSessionKey.js");
Object.defineProperty(exports, "createSessionKey", { enumerable: true, get: function () { return createSessionKey_js_1.createSessionKey; } });
Object.defineProperty(exports, "isCreateSessionKeySupported", { enumerable: true, get: function () { return createSessionKey_js_1.isCreateSessionKeySupported; } });
var index_js_1 = require("../../wallets/in-app/native/auth/index.js");
Object.defineProperty(exports, "authenticate", { enumerable: true, get: function () { return index_js_1.authenticate; } });
Object.defineProperty(exports, "getProfiles", { enumerable: true, get: function () { return index_js_1.getProfiles; } });
Object.defineProperty(exports, "getUserEmail", { enumerable: true, get: function () { return index_js_1.getUserEmail; } });
Object.defineProperty(exports, "getUserPhoneNumber", { enumerable: true, get: function () { return index_js_1.getUserPhoneNumber; } });
Object.defineProperty(exports, "linkProfile", { enumerable: true, get: function () { return index_js_1.linkProfile; } });
Object.defineProperty(exports, "preAuthenticate", { enumerable: true, get: function () { return index_js_1.preAuthenticate; } });
Object.defineProperty(exports, "unlinkProfile", { enumerable: true, get: function () { return index_js_1.unlinkProfile; } });
var passkeys_js_1 = require("../../wallets/in-app/native/auth/passkeys.js");
Object.defineProperty(exports, "hasStoredPasskey", { enumerable: true, get: function () { return passkeys_js_1.hasStoredPasskey; } });
var in_app_js_1 = require("../../wallets/in-app/native/in-app.js");
Object.defineProperty(exports, "inAppWallet", { enumerable: true, get: function () { return in_app_js_1.inAppWallet; } });
//# sourceMappingURL=in-app.native.js.map