"use strict";
// This file is auto-generated by @hey-api/openapi-ts
Object.defineProperty(exports, "__esModule", { value: true });
exports.searchSolanaActivityLogs = exports.getSolanaActivityLogs = exports.searchSolanaTransactions = exports.getSolanaTransactions = exports.searchActivityLogs = exports.getActivityLogs = exports.searchTransactions = exports.getTransactionAnalyticsSummary = exports.getTransactionAnalytics = exports.getTransactions = exports.signSolanaMessage = exports.createSolanaAccount = exports.listSolanaAccounts = exports.createAccount = exports.listAccounts = exports.cancelTransaction = exports.signSolanaTransaction = exports.sendSolanaTransaction = exports.encodeContract = exports.readContract = exports.signTypedData = exports.signMessage = exports.sendTransaction = exports.writeContract = void 0;
const client_gen_js_1 = require("./client.gen.js");
/**
 * Write Contract
 * Call a contract function with a transaction
 */
const writeContract = (options) => {
    return (options.client ?? client_gen_js_1.client).post({
        security: [
            {
                name: "x-secret-key",
                type: "apiKey",
            },
        ],
        url: "/v1/write/contract",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};
exports.writeContract = writeContract;
/**
 * Write Transaction
 * Execute raw transactions
 */
const sendTransaction = (options) => {
    return (options.client ?? client_gen_js_1.client).post({
        security: [
            {
                name: "x-secret-key",
                type: "apiKey",
            },
        ],
        url: "/v1/write/transaction",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};
exports.sendTransaction = sendTransaction;
/**
 * Sign Message
 * Sign messages using either EOA or Smart Account
 */
const signMessage = (options) => {
    return (options.client ?? client_gen_js_1.client).post({
        security: [
            {
                name: "x-secret-key",
                type: "apiKey",
            },
        ],
        url: "/v1/sign/message",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};
exports.signMessage = signMessage;
/**
 * Sign Typed Data
 * Sign EIP-712 typed data using either EOA or Smart Account
 */
const signTypedData = (options) => {
    return (options.client ?? client_gen_js_1.client).post({
        security: [
            {
                name: "x-secret-key",
                type: "apiKey",
            },
        ],
        url: "/v1/sign/typed-data",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};
exports.signTypedData = signTypedData;
/**
 * Read Contract
 * Read from smart contracts with intelligent execution strategy:
 * - Single calls: Always executed directly for efficiency
 * - Multiple calls: Uses multicall by default, or direct calls if disabled
 * - Failed preparations: Returns preparation errors directly
 *
 * If multicall is not specified, it will be used by default. In case of multicall related errors, engine will fallback to direct calls.
 * Only in the case where multicall is explicitly enabled, engine will not fallback to direct calls.
 */
const readContract = (options) => {
    return (options.client ?? client_gen_js_1.client).post({
        security: [
            {
                name: "x-secret-key",
                type: "apiKey",
            },
        ],
        url: "/v1/read/contract",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};
exports.readContract = readContract;
/**
 * Encode Contract
 * Encode contract function calls without execution
 */
const encodeContract = (options) => {
    return (options.client ?? client_gen_js_1.client).post({
        security: [
            {
                name: "x-secret-key",
                type: "apiKey",
            },
        ],
        url: "/v1/encode/contract",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};
exports.encodeContract = encodeContract;
/**
 * Send Solana Transaction
 * Execute a Solana transaction with custom instructions
 */
const sendSolanaTransaction = (options) => {
    return (options.client ?? client_gen_js_1.client).post({
        security: [
            {
                name: "x-secret-key",
                type: "apiKey",
            },
        ],
        url: "/v1/solana/transaction",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};
exports.sendSolanaTransaction = sendSolanaTransaction;
/**
 * Sign Solana Transaction
 * Sign a Solana transaction without broadcasting it
 */
const signSolanaTransaction = (options) => {
    return (options.client ?? client_gen_js_1.client).post({
        security: [
            {
                name: "x-secret-key",
                type: "apiKey",
            },
        ],
        url: "/v1/solana/sign/transaction",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};
exports.signSolanaTransaction = signSolanaTransaction;
/**
 * Cancel Transaction
 * Attempt to cancel a queued transaction. Transactions that have been sent and are waiting for mine cannot be cancelled.
 */
const cancelTransaction = (options) => {
    return (options.client ?? client_gen_js_1.client).post({
        security: [
            {
                name: "x-secret-key",
                type: "apiKey",
            },
        ],
        url: "/v1/transactions/{id}/cancel",
        ...options,
    });
};
exports.cancelTransaction = cancelTransaction;
/**
 * List Server Wallets
 * List all engine server wallets for the current project. Returns an array of EOA addresses with their corresponding predicted smart account addresses.
 */
const listAccounts = (options) => {
    return (options?.client ?? client_gen_js_1.client).get({
        security: [
            {
                name: "x-secret-key",
                type: "apiKey",
            },
        ],
        url: "/v1/accounts",
        ...options,
    });
};
exports.listAccounts = listAccounts;
/**
 * Get or Create Server Wallet
 * Create a new engine server wallet or retrieve an existing one. If the EOA already exists for the given label, it will be returned without creating a new one.
 */
const createAccount = (options) => {
    return (options?.client ?? client_gen_js_1.client).post({
        security: [
            {
                name: "x-secret-key",
                type: "apiKey",
            },
        ],
        url: "/v1/accounts",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options?.headers,
        },
    });
};
exports.createAccount = createAccount;
/**
 * List Solana Accounts
 * List all Solana wallets provisioned for the project.
 */
const listSolanaAccounts = (options) => {
    return (options?.client ?? client_gen_js_1.client).get({
        security: [
            {
                name: "x-secret-key",
                type: "apiKey",
            },
        ],
        url: "/v1/solana/accounts",
        ...options,
    });
};
exports.listSolanaAccounts = listSolanaAccounts;
/**
 * Get or Create Solana Account
 * Create a new solana wallet in the vault or return the existing wallet for a given label.
 */
const createSolanaAccount = (options) => {
    return (options?.client ?? client_gen_js_1.client).post({
        security: [
            {
                name: "x-secret-key",
                type: "apiKey",
            },
        ],
        url: "/v1/solana/accounts",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options?.headers,
        },
    });
};
exports.createSolanaAccount = createSolanaAccount;
/**
 * Sign Solana Message
 * Sign an arbitrary message with a Solana wallet.
 */
const signSolanaMessage = (options) => {
    return (options?.client ?? client_gen_js_1.client).post({
        security: [
            {
                name: "x-secret-key",
                type: "apiKey",
            },
        ],
        url: "/v1/solana/sign-message",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options?.headers,
        },
    });
};
exports.signSolanaMessage = signSolanaMessage;
/**
 * Get Transactions
 * Search transactions with various filters and pagination
 */
const getTransactions = (options) => {
    return (options?.client ?? client_gen_js_1.client).get({
        security: [
            {
                name: "x-secret-key",
                type: "apiKey",
            },
        ],
        url: "/v1/transactions",
        ...options,
    });
};
exports.getTransactions = getTransactions;
/**
 * Transaction Analytics
 * Get transaction count analytics over time with filtering
 */
const getTransactionAnalytics = (options) => {
    return (options?.client ?? client_gen_js_1.client).post({
        security: [
            {
                name: "x-secret-key",
                type: "apiKey",
            },
        ],
        url: "/v1/transactions/analytics",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options?.headers,
        },
    });
};
exports.getTransactionAnalytics = getTransactionAnalytics;
/**
 * Transaction Analytics Summary
 * Get a summary (total count and total gas calculation) for transactions within a time range, supporting complex nested filters.
 */
const getTransactionAnalyticsSummary = (options) => {
    return (options?.client ?? client_gen_js_1.client).post({
        security: [
            {
                name: "x-secret-key",
                type: "apiKey",
            },
        ],
        url: "/v1/transactions/analytics-summary",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options?.headers,
        },
    });
};
exports.getTransactionAnalyticsSummary = getTransactionAnalyticsSummary;
/**
 * Search Transactions
 * Advanced search for transactions with complex nested filters
 */
const searchTransactions = (options) => {
    return (options?.client ?? client_gen_js_1.client).post({
        security: [
            {
                name: "x-secret-key",
                type: "apiKey",
            },
        ],
        url: "/v1/transactions/search",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options?.headers,
        },
    });
};
exports.searchTransactions = searchTransactions;
/**
 * Get Activity Logs
 * Get paginated activity logs for a specific transaction with tenancy enforcement
 */
const getActivityLogs = (options) => {
    return (options.client ?? client_gen_js_1.client).get({
        security: [
            {
                name: "x-secret-key",
                type: "apiKey",
            },
        ],
        url: "/v1/transactions/activity-logs",
        ...options,
    });
};
exports.getActivityLogs = getActivityLogs;
/**
 * Search Activity Logs
 * Search activity logs across transactions with advanced filtering and tenancy enforcement
 */
const searchActivityLogs = (options) => {
    return (options?.client ?? client_gen_js_1.client).post({
        security: [
            {
                name: "x-secret-key",
                type: "apiKey",
            },
        ],
        url: "/v1/transactions/activity-logs/search",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options?.headers,
        },
    });
};
exports.searchActivityLogs = searchActivityLogs;
/**
 * Get Solana Transactions
 * Search Solana transactions with various filters and pagination
 */
const getSolanaTransactions = (options) => {
    return (options?.client ?? client_gen_js_1.client).get({
        security: [
            {
                name: "x-secret-key",
                type: "apiKey",
            },
        ],
        url: "/v1/solana/transactions",
        ...options,
    });
};
exports.getSolanaTransactions = getSolanaTransactions;
/**
 * Search Solana Transactions
 * Advanced search for Solana transactions with complex nested filters
 */
const searchSolanaTransactions = (options) => {
    return (options?.client ?? client_gen_js_1.client).post({
        security: [
            {
                name: "x-secret-key",
                type: "apiKey",
            },
        ],
        url: "/v1/solana/transactions/search",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options?.headers,
        },
    });
};
exports.searchSolanaTransactions = searchSolanaTransactions;
/**
 * Get Solana Activity Logs
 * Get paginated activity logs for a specific Solana transaction with tenancy enforcement
 */
const getSolanaActivityLogs = (options) => {
    return (options.client ?? client_gen_js_1.client).get({
        security: [
            {
                name: "x-secret-key",
                type: "apiKey",
            },
        ],
        url: "/v1/solana/transactions/activity-logs",
        ...options,
    });
};
exports.getSolanaActivityLogs = getSolanaActivityLogs;
/**
 * Search Solana Activity Logs
 * Search Solana activity logs across transactions with advanced filtering and tenancy enforcement
 */
const searchSolanaActivityLogs = (options) => {
    return (options?.client ?? client_gen_js_1.client).post({
        security: [
            {
                name: "x-secret-key",
                type: "apiKey",
            },
        ],
        url: "/v1/solana/transactions/activity-logs/search",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options?.headers,
        },
    });
};
exports.searchSolanaActivityLogs = searchSolanaActivityLogs;
//# sourceMappingURL=sdk.gen.js.map